# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

defaults: &dev_defaults
  facebook:
    app_id: 558889160934969
    secret: a8cc1e2ee43e949af1ffd62a8f86186c

development:
  <<: *dev_defaults
  secret_key_base: 94b4d13ff71b9cc92529777bf6b4a0f47b460f3972fbace753e723d84d2312a483921c63ac582091077b523460e57a679b93041da06515d27d811e871f6e7815
  host: localhost:3000

test:
  <<: *dev_defaults
  secret_key_base: 43964ce3440c6abfc85a81088382323c4129b2113fffd5c45804a0f9851fb617190521a59465e3c61c35b10d3289f01e0ab239e29538bad0b7aa4ce40b0fb175
  host: test.givdo.com

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  host: <%= ENV["GIVDO_HOST"] %>
  facebook:
    app_id: <%= ENV["FACEBOOK_APP_ID"] %>
    secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
